### PR TITLE
Installer slideshow to set pixmap scaled width

### PR DESCRIPTION
**Pull request by christiand992**
* Gets the installer wizard width and sets pixmap to scaledToWidth
* Removes change to label_slide_icon verstretch, which... doesn't do what I thought it did...

Please inspect these changes closely; C++ noob wondering further into the forest....

### CODE REVIEW

**Comment by christiand992** [comment]
This change was tested using multiple screen resolutions and did successfully scale the image by width, without obviously distorting the image.

However, I'm unsure that there isn't a better way to grab the installer's width attributes. I attempted a few things, like trying to get the iconlabel's (aka label_slide_icon) attributes, but those were unset. The only place I found that returned any size attributes was the Installer which has it's geometry set in main.ccp. If there's a better approach, please reject this PR. Some pointers would be even better. Thanks!

**Comment by pkgdemon** [comment]
Merging for testing

**Comment by beanpole135** [comment]
That should work fine, but yes, using the label geometry would be the "proper" way to do it.
In order for the geometry to be set on the label though, the slideshow "setting" function you are adjusting needs to be delayed a tiny bit until *right after* the slideshow labels/widgets are actually made visible (that is when Qt does all the sizing/auto-adjust stuff). 
The alternative to this is to pass a QSize in as an additional argument to this function which is used for the image scaling, and then the main installer UI can work out the sizing itself and just pass that metric along. This would be my recommendation, since it will not rely on the underlying Qt timing issues, and the main UI already has all the various geometry info available before it requests the new page.

**Comment by christiand992** [comment]
Thank you for the pointers Ken, I shall attempt tackling your suggested changes. If I should open an issue and assign it to myself, referencing this PR, let me know.

**Pull request merged**
